initial:
  name: 2d_initial

  sigma_noise: 0.01
  bnn:
    layers:
      1:
        type: gaussian
        weight: 1.
        bias: 1.
        activation: tanh
        layer_size: 40
      2:
        type: gaussian
        weight: 1.
        bias: 1.
        activation: tanh
        layer_size: 10
      3:
        type: gaussian
        weight: 1.
        bias: 1.
        activation: tanh
        layer_size: 50
      4:
        type: gaussian
        weight: 1.
        bias: 1.
        activation: 
        layer_size: 40
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 10000
    random_seed: 42
