initial:
  name: 2d_initial

  sigma_noise: 0.01
  bnn:
    layers:
      1:
        type: cauchy
        weight: 1.0
        bias: 1.0
        activation: tanh
        layer_size: 400
      2:
        type: cauchy
        weight: 1.0
        bias: 1.0
        activation: tanh
        layer_size: 800
      3:
        type: cauchy
        weight: 1.0
        bias: 1.0
        activation: tanh
        layer_size: 400
      4:
        type: cauchy
        weight: 1.0
        bias: 1.0
        activation: 
        layer_size: 800
  training_parameters:
    learning_rate: 0.00001
    svi_num_iterations: 100000
    random_seed: 42