initial:
  name: 2d_initial

  sigma_noise: 0.01
  bnn:
    layers:
      1:
        type: cauchy
        weight: 10.
        bias: 10.
        activation: tanh
        layer_size: 200
      2:
        type: cauchy
        weight: 10.
        bias: 10.
        activation: tanh
        layer_size: 800
      3:
        type: cauchy
        weight: 0.01
        bias: 0.01
        activation: 
        layer_size: 200
  training_parameters:
    learning_rate: 0.001
    svi_num_iterations: 100000
    random_seed: 42
