continuous:
  name: continuous_high_sigma
  problem: continuous
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:
      1:
        type: gaussian
        weight: 3.0
        bias: 3.0
        activation: tanh
        layer_size: 100
      2:
        type: gaussian
        weight: 3.0
        bias: 3.0
        activation: tanh
        layer_size: 80
      3:
        type: gaussian
        weight: 3.0
        bias: 3.0
        activation: tanh
        layer_size: 40
      4:
        type: gaussian
        weight: 0.5
        bias: 0.05
        activation: 
        layer_size: 80
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 8000
    random_seed: 42