iterations_5000:
  name: discrete_iterations_5000
  problem: discrete
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:
      1:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 40
      2:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 80
      3:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 40
      4:
        type: cauchy
        weight: 2.0
        bias: 3.0
        activation: 
        layer_size: 80
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 5000
    random_seed: 42

iterations_10000:
  name: discrete_iterations_10000
  problem: discrete
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:
      1:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 40
      2:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 80
      3:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 40
      4:
        type: cauchy
        weight: 2.0
        bias: 3.0
        activation: 
        layer_size: 80
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 10000
    random_seed: 42

iterations_20000:
  name: discrete_iterations_20000
  problem: discrete
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:
      1:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 40
      2:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 80
      3:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 40
      4:
        type: cauchy
        weight: 2.0
        bias: 3.0
        activation: 
        layer_size: 80
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 20000
    random_seed: 42

iterations_30000:
  name: discrete_iterations_30000
  problem: discrete
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:
      1:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 40
      2:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 80
      3:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 40
      4:
        type: cauchy
        weight: 2.0
        bias: 3.0
        activation: 
        layer_size: 80
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 30000
    random_seed: 42
