sigma_002:
  name: discrete_sigma_002
  problem: discrete
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.02
  bnn:
    layers:
      1:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 40
      2:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 80
      3:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 40
      4:
        type: cauchy
        weight: 2.0
        bias: 3.0
        activation: 
        layer_size: 80
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 8000
    random_seed: 42

sigma_005:
  name: discrete_sigma_005
  problem: discrete
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.05
  bnn:
    layers:
      1:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 40
      2:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 80
      3:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 40
      4:
        type: cauchy
        weight: 2.0
        bias: 3.0
        activation: 
        layer_size: 80
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 8000
    random_seed: 42

sigma_01:
  name: discrete_sigma_01
  problem: discrete
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.1
  bnn:
    layers:
      1:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 40
      2:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 80
      3:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 40
      4:
        type: cauchy
        weight: 2.0
        bias: 3.0
        activation: 
        layer_size: 80
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 8000
    random_seed: 42
