
continuous:
  name: continuous_high_sigma
  problem: continuous
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:
      1:
        type: gaussian
        weight: 10.0
        bias: 10.0
        activation: tanh
        layer_size: 40
      2:
        type: gaussian
        weight: 10.0
        bias: 10.0
        activation: tanh
        layer_size: 80
      3:
        type: gaussian
        weight: 10.0
        bias: 10.0
        activation: tanh
        layer_size: 40
      4:
        type: gaussian
        weight: 10.0
        bias: 10.0
        activation: 
        layer_size: 80
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 10000
    random_seed: 42

discrete:
  name: discrete_high_sigma
  problem: discrete
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:
      1:
        type: gaussian
        weight: 10.0
        bias: 10.0
        activation: tanh
        layer_size: 40
      2:
        type: gaussian
        weight: 10.0
        bias: 10.0
        activation: tanh
        layer_size: 80
      3:
        type: gaussian
        weight: 10.0
        bias: 10.0
        activation: tanh
        layer_size: 40
      4:
        type: gaussian
        weight: 10.0
        bias: 10.0
        activation: 
        layer_size: 80
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 10000
    random_seed: 42

combined:
  name: combined_high_sigma
  problem: combined
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:
      1:
        type: gaussian
        weight: 10.0
        bias: 10.0
        activation: tanh
        layer_size: 40
      2:
        type: gaussian
        weight: 10.0
        bias: 10.0
        activation: tanh
        layer_size: 80
      3:
        type: gaussian
        weight: 10.0
        bias: 10.0
        activation: tanh
        layer_size: 40
      4:
        type: gaussian
        weight: 10.0
        bias: 10.0
        activation: 
        layer_size: 80
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 10000
    random_seed: 42