
continuous:
  name: mcmc_continuous_initial
  problem: continuous
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:
      1:
        type: gaussian
        weight: 1.0
        bias: 1.0
        activation: tanh
        layer_size: 40
      2:
        type: gaussian
        weight: 1.0
        bias: 1.0
        activation: tanh
        layer_size: 80
      3:
        type: gaussian
        weight: 1.0
        bias: 1.0
        activation: tanh
        layer_size: 40
      4:
        type: gaussian
        weight: 1.0
        bias: 1.0
        activation: 
        layer_size: 80
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 8000
    random_seed: 42

discrete:
  name: mcmc_discrete_initial
  problem: discrete
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:
      1:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 40
      2:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 80
      3:
        type: cauchy
        weight: 5.0
        bias: 0.1
        activation: tanh
        layer_size: 40
      4:
        type: cauchy
        weight: 2.0
        bias: 3.0
        activation: 
        layer_size: 80
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 8000
    random_seed: 42

combined:
  name: mcmc_combined_initial
  problem: combined
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:
      1:
        type: gaussian
        weight: 1.0
        bias: 1.0
        activation: tanh
        layer_size: 40
      2:
        type: cauchy
        weight: 1.0
        bias: 1.0
        activation: tanh
        layer_size: 80
      3:
        type: cauchy
        weight: 1.0
        bias: 1.0
        activation: tanh
        layer_size: 40
      4:
        type: gaussian
        weight: 2.0
        bias: 2.0
        activation: 
        layer_size: 80
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 8000
    random_seed: 42