continuous_weights_biases_v1:
  name: continuous_weights_biases_v1
  problem: continuous
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:    
      1:
        type: gaussian
        weight: 0.5
        bias: 0.5
        activation: tanh
        layer_size: 40
      2:
        type: gaussian
        weight: 1.5
        bias: 0.2
        activation: tanh
        layer_size: 80
      3:
        type: gaussian
        weight: 0.8
        bias: 0.7
        activation: tanh
        layer_size: 40
      4:
        type: gaussian
        weight: 1.2
        bias: 1.3
        activation: 
        layer_size: 80
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 20000
    random_seed: 42

continuous_weights_biases_v2:
  name: continuous_weights_biases_v2
  problem: continuous
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:    
      1:
        type: gaussian
        weight: 0.8
        bias: 0.4
        activation: tanh
        layer_size: 50
      2:
        type: gaussian
        weight: 1.2
        bias: 0.6
        activation: tanh
        layer_size: 70
      3:
        type: gaussian
        weight: 1.0
        bias: 0.5
        activation: tanh
        layer_size: 50
      4:
        type: gaussian
        weight: 1.5
        bias: 0.9
        activation: 
        layer_size: 90
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 20000
    random_seed: 42

continuous_weights_biases_v3:
  name: continuous_weights_biases_v3
  problem: continuous
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:    
      1:
        type: gaussian
        weight: 0.6
        bias: 0.3
        activation: tanh
        layer_size: 30
      2:
        type: gaussian
        weight: 1.0
        bias: 0.5
        activation: tanh
        layer_size: 60
      3:
        type: gaussian
        weight: 0.9
        bias: 0.4
        activation: tanh
        layer_size: 30
      4:
        type: gaussian
        weight: 1.3
        bias: 1.1
        activation: 
        layer_size: 70
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 20000
    random_seed: 42

continuous_weights_biases_v4:
  name: continuous_weights_biases_v4
  problem: continuous
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:    
      1:
        type: gaussian
        weight: 1.0
        bias: 0.6
        activation: tanh
        layer_size: 45
      2:
        type: gaussian
        weight: 1.4
        bias: 0.7
        activation: tanh
        layer_size: 85
      3:
        type: gaussian
        weight: 1.2
        bias: 0.8
        activation: tanh
        layer_size: 45
      4:
        type: gaussian
        weight: 1.0
        bias: 1.0
        activation: 
        layer_size: 85
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 20000
    random_seed: 42

continuous_weights_biases_v5:
  name: continuous_weights_biases_v5
  problem: continuous
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:    
      1:
        type: gaussian
        weight: 0.7
        bias: 0.2
        activation: tanh
        layer_size: 35
      2:
        type: gaussian
        weight: 1.3
        bias: 0.4
        activation: tanh
        layer_size: 75
      3:
        type: gaussian
        weight: 1.1
        bias: 0.6
        activation: tanh
        layer_size: 35
      4:
        type: gaussian
        weight: 1.4
        bias: 1.2
        activation: 
        layer_size: 85
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 20000
    random_seed: 42

continuous_weights_biases_v6:
  name: continuous_weights_biases_v6
  problem: continuous
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:    
      1:
        type: gaussian
        weight: 0.9
        bias: 0.5
        activation: tanh
        layer_size: 50
      2:
        type: gaussian
        weight: 1.1
        bias: 0.3
        activation: tanh
        layer_size: 90
      3:
        type: gaussian
        weight: 1.0
        bias: 0.7
        activation: tanh
        layer_size: 50
      4:
        type: gaussian
        weight: 1.3
        bias: 1.4
        activation: 
        layer_size: 90
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 20000
    random_seed: 42

continuous_weights_biases_v7:
  name: continuous_weights_biases_v7
  problem: continuous
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:    
      1:
        type: gaussian
        weight: 1.2
        bias: 0.8
        activation: tanh
        layer_size: 40
      2:
        type: gaussian
        weight: 1.0
        bias: 0.4
        activation: tanh
        layer_size: 80
      3:
        type: gaussian
        weight: 0.8
        bias: 0.3
        activation: tanh
        layer_size: 40
      4:
        type: gaussian
        weight: 1.5
        bias: 1.1
        activation: 
        layer_size: 80
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 20000
    random_seed: 42

continuous_weights_biases_v8:
  name: continuous_weights_biases_v8
  problem: continuous
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:    
      1:
        type: gaussian
        weight: 0.6
        bias: 0.4
        activation: tanh
        layer_size: 45
      2:
        type: gaussian
        weight: 1.3
        bias: 0.6
        activation: tanh
        layer_size: 85
      3:
        type: gaussian
        weight: 1.1
        bias: 0.5
        activation: tanh
        layer_size: 45
      4:
        type: gaussian
        weight: 1.0
        bias: 1.2
        activation: 
        layer_size: 85
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 20000
    random_seed: 42

continuous_weights_biases_v9:
  name: continuous_weights_biases_v9
  problem: continuous
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:    
      1:
        type: gaussian
        weight: 0.7
        bias: 0.3
        activation: tanh
        layer_size: 55
      2:
        type: gaussian
        weight: 1.4
        bias: 0.5
        activation: tanh
        layer_size: 75
      3:
        type: gaussian
        weight: 1.2
        bias: 0.6
        activation: tanh
        layer_size: 55
      4:
        type: gaussian
        weight: 1.1
        bias: 1.0
        activation: 
        layer_size: 75
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 20000
    random_seed: 42

continuous_weights_biases_v10:
  name: continuous_weights_biases_v10
  problem: continuous
  n_t: 100
  n_y: 100
  domain: [-1, 1]
  sigma_noise: 0.01
  bnn:
    layers:    
      1:
        type: gaussian
        weight: 0.5
        bias: 0.7
        activation: tanh
        layer_size: 60
      2:
        type: gaussian
        weight: 1.2
        bias: 0.8
        activation: tanh
        layer_size: 90
      3:
        type: gaussian
        weight: 0.9
        bias: 0.9
        activation: tanh
        layer_size: 60
      4:
        type: gaussian
        weight: 1.3
        bias: 1.2
        activation: 
        layer_size: 90
  training_parameters:
    learning_rate: 0.01
    svi_num_iterations: 20000
    random_seed: 42
